name: Moodle Portability Test

on: [push, pull_request]

jobs:
  test-on-multiple-os:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout kode
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, intl
        coverage: none

    - name: Install dependency (kalo composer)
      run: |
        if [ -f composer.json ]; then
          composer install
        else
          echo "Tidak pakai Composer"
        fi

    - name: Jalankan tes (kalo PHPUnit)
      run: |
        if [ -f vendor/bin/phpunit ]; then
          vendor/bin/phpunit
        else
          echo "Tes tidak ditemukan, lewati step ini"
        fi
